apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: swagger
  namespace: default
spec:
  rules:
    - https:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: swagger
                port:
                  number: 8080
