kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: swagger-ui
  namespace: swagger-ui
  ownerReferences:
    - apiVersion: networking.k8s.io/v1
      kind: Ingress
      name: swagger-ui
      controller: true
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: swagger-ui
                port:
                  number: 8080
