apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: swagger-ui
  namespace: swagger-ui
spec:
  rules:
    - https:
        paths:
          - path: /swagger-ui
            pathType: Prefix
            backend:
              service:
                name: swagger-ui
                port:
                  number: 8080
