apiVersion: v1
kind: Service
metadata:
  labels:
    app: swagger
  name: swagger
  namespace: default
  resourceVersion: "65565"
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: swagger
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}