kind: PersistentVolume
apiVersion: v1
metadata:
  name: swagger-ui-pv-volume
  labels:
    type: local
    app: swagger-ui
spec:
  volumeMode: Filesystem
  storageClassName: gp2
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    kind: PersistentVolumeClaim
    namespace: swagger-ui
    name: swagger-ui-pv-claim