kind: Service
apiVersion: v1
metadata:
  name: swagger-ui
  namespace: swagger-ui
  labels:
    app: swagger-ui
    app.kubernetes.io/component: swagger-ui
    app.kubernetes.io/instance: swagger-ui
    app.kubernetes.io/name: swagger-ui
    app.kubernetes.io/part-of: swagger-ui-app
    app.openshift.io/runtime-version: latest
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: swagger-ui
    deployment: swagger-ui