kind: Service
apiVersion: v1
metadata:
  name: swagger-ui
  namespace: default
  labels:
    app: swagger-ui
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  internalTrafficPolicy: Cluster
  type: LoadBalancer
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: swagger-ui
    deployment: swagger-ui