apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: swagger-ui-pv-claim
  labels:
    app: swagger-ui
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 250Mi